language: cpp

cache:
  ccache: true
  timeout: 1000

matrix:
  include:
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=debian DOCKERIMG=debian:stretch
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=debian DOCKERIMG=debian:stretch
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=fedora DOCKERIMG=fedora:24 FEDORAVER=24
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=fedora DOCKERIMG=fedora:24 FEDORAVER=24
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=fedora DOCKERIMG=fedora:25 FEDORAVER=25
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=fedora DOCKERIMG=fedora:25 FEDORAVER=25
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=opensuse DOCKERIMG=opensuse:42.2
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=opensuse DOCKERIMG=opensuse:42.2
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=opensuse DOCKERIMG=opensuse:tumbleweed
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=opensuse DOCKERIMG=opensuse:tumbleweed
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:trusty
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:trusty
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:xenial
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:xenial
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:yakkety
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:yakkety
  - os: linux
    sudo: required
    services:
      - docker
    compiler: gcc
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:zesty
  - os: linux
    sudo: required
    services:
      - docker
    compiler: clang
    env:
      - DOCKERSYS=debian DOCKERIMG=ubuntu:zesty
  - os: osx
    osx_image: xcode8
    compiler: clang
    env:
      - DISABLE_CCACHE=1
  - os: osx
    osx_image: xcode8.1
    compiler: clang
  - os: osx
    osx_image: xcode8.2
    compiler: clang
  - language: android
    jdk: oraclejdk8
    android:
      components:
        - tools
        - platform-tools
        - build-tools-22.0.1
        - android-22
        - sys-img-armeabi-v7a-android-22
    env:
      - ANDROID_BUILD=1
      - QTVER=5.8.0

before_install: |
  if [ -z "${ANDROID_BUILD}" ]; then
    if [ "${TRAVIS_OS_NAME}" = linux ]; then
      docker pull ${DOCKERIMG}
      docker ps -a
      docker run -it -d -v ${PWD}:/sources -v $HOME/.ccache:/ccache -e CCACHE_DIR=/ccache -w /sources --name ${DOCKERSYS} ${DOCKERIMG} /bin/sh
    elif [ "${TRAVIS_OS_NAME}" = osx ]; then
      brew update
      brew upgrade
    fi
  fi

install:
  - ports/ci/travis/install_deps.sh

before_script: |
  if [ "${ANDROID_BUILD}" = 1 ]; then
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=android-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=android-clang
    fi
  elif [ "${TRAVIS_OS_NAME}" = linux ]; then
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=linux-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=linux-clang
    fi
  elif [ "${TRAVIS_OS_NAME}" = osx ]; then
    brew link --force qt5
    if [ "${CXX}" = g++ ]; then
      export COMPILESPEC=macx-g++
    elif [ "${CXX}" = clang++ ]; then
      export COMPILESPEC=macx-clang
    fi
  fi

script:
  - ports/ci/travis/build.sh

branches:
  only:
    - master

notifications:
  recipients:
    - hipersayan.x@gmail.com
  email:
    on_success: change
    on_failure: change
